### ISSUE TITLE
Expectations chapter needs research staff section fleshed out

### ISSUE THREAD

**Issue by gavinfay** [thefaylab/lab-manual#1]
The research staff section of the [expectations chapter](https://github.com/thefaylab/lab-manual/blob/master/05-expectations.Rmd) needs adding to.
Ashleigh, can you help?

**Comment by AshleighNovak** [comment]
Added some content - is this enough? 

I'm wondering if there should be a separate section for Lab Manager. Not sure if future research staff you bring in will also fill the lab manager role?

**Comment by gavinfay** [comment]
Thanks. I like these. I think I will change further to make a bit more generic and refer to specific duties and responsibilities are outlined in the position descriptions. These positions are a little different from say students where language in the university RAship contracts are more fuzzy.
