### ISSUE TITLE
Off-boarding chapter needs to be fleshed out

### ISSUE THREAD

**Issue by AshleighNovak** [thefaylab/lab-manual#11]
Gavin - I think you should take the reins on this chapter as I am not sure what to put for each topic. Thanks! :slightly_smiling_face:

**Comment by gavinfay** [comment]
Draft of this chapter added. @AshleighNovak please review. :)

**Comment by AshleighNovak** [comment]
Looks great to me! I added the offboarding checklist so I am closing this for now.
