### ISSUE TITLE
Onboarding chapter needs links to checklists

### ISSUE THREAD

**Issue by gavinfay** [thefaylab/lab-manual#12]
It would be good if the [onboarding chapter](https://github.com/thefaylab/lab-manual/blob/master/04-onboarding.Rmd) contained links to Google docs with checklists for onaboarding steps.
Probably want one for grad students and one for research staff. There'll be some duplicaton in these lists but several steps that are unique to each position type.

**Comment by AshleighNovak** [comment]
Added link with a checklist for research staff. Just asked Lucy (@lumcginnis) to help populate the student onboarding checklist!

Will close issue when the draft checklist is complete.

**Comment by AshleighNovak** [comment]
This is mostly complete, so I am closing. Tammy has reviewed it. Will populate the undergraduate section when we hire a new undergrad this fall (and ask Tabitha as well).
