### ISSUE TITLE
Intro and How we Work

### ISSUE THREAD

**Issue by gavinfay** [thefaylab/lab-manual#2]
The [how we work](https://github.com/thefaylab/lab-manual/blob/master/01-intro-how-we-work.Rmd) chapter needs to be created.

**Comment by gavinfay** [comment]
@AshleighNovak please add the draft of this as discussed.

**Comment by gavinfay** [comment]
Gavin [added placeholder text](https://github.com/thefaylab/lab-manual/commit/ea460c25def6667af1da3dd6618f7b89c5817835).

**Comment by AshleighNovak** [comment]
Added some content. 

Gavin - need content for how we send things to you.

**Comment by gavinfay** [comment]
Added some material for this section - I think it needs paring down to avoid duplication with content elsewhere. @AshleighNovak can you help with this please?
