### ISSUE TITLE
Review draft of Academics Chapter

### ISSUE THREAD

**Issue by gavinfay** [thefaylab/lab-manual#22]
Initial draft of academics chapter added. @AshleighNovak please review and edit this and suggest needed additions.  Once done, please assign a reviewer. Thanks!

**Comment by AshleighNovak** [comment]
Do you have any expectations for number of publications for masters students? I think it looks good besides the pieces that need to be filled in! I just made some minor comments.

@tsilva4 would you mind reviewing this chapter please?

**Comment by tammylsilva** [comment]
Looks good overall! Just a few things / suggestions.

Sections on thesis guidance:
-here is a link to University thesis templates: https://www.umassd.edu/graduate/student-resources/

PhD students section intro:
-Could also include the advantages to having your chapters published before your dissertation defense (less writing for your thesis, less likely that your committee will require additional work if your chapter (s) have been peer-reviewed and published)

PhD student section on pre-proposals:
-Should the last sentence be deleted? I believe a written pre-proposal is a requirement and the Dissertation Proposal section also seems to indicate this.

**Comment by AshleighNovak** [comment]
Made @tammylsilva's comments so closing for now 👍
