### ISSUE TITLE
Customize pins for for thefaylab 

### ISSUE THREAD

**Issue by lumcginnis** [thefaylab/lab-manual#26]
Pin lab-manual and lab-chat. Get labhub off that home screen so it doesn't confuse anyone else!

Gavin I assume you have the login for this account so I've assigned you this task

![image](https://user-images.githubusercontent.com/65247908/135147911-b9307f71-1d9e-4a72-9038-ec7aa9403a63.png)

**Comment by gavinfay** [comment]
Done. lab-chat is a private repo so can't be pinned but added pins for enough others to squash the labhub. 🏏
