### ISSUE TITLE
Review lab culture

### ISSUE THREAD

**Issue by gavinfay** [thefaylab/lab-manual#3]
Please review [lab culture](https://github.com/thefaylab/lab-manual/blob/master/02-lab-culture-philosophy.Rmd) chapter.

**Comment by AshleighNovak** [comment]
Some small changes, otherwise looks great!

**Comment by gavinfay** [comment]
These changes look good. Thanks!

Quick reminder to use informative and self-explanatory commit messages. e.g.

> Minor editing fixes, small changes to wording 

could be changed to

> makes minor wording edits to lab culture

The latter references what the changes were made for without having to inspect the commit.
