### ISSUE TITLE
Code of conduct awaiting approval from SMAST & DEI

### ISSUE THREAD

**Issue by gavinfay** [thefaylab/lab-manual#4]
The [code of conduct](https://github.com/thefaylab/lab-manual/blob/master/03-code-of-conduct.Rmd) chapter is populated, but is awaiting review from Mike Marino and David Gomes.

**Comment by AshleighNovak** [comment]
I think this is all set now we have heard from Cecilia? @gavinfay to confirm and close issue. Thanks!

**Comment by AshleighNovak** [comment]
All set! Discussed in lab meeting. Closing!
