### ISSUE TITLE
10/21 Manual Review - Resources

### ISSUE THREAD

**Issue by CataRoman** [thefaylab/lab-manual#50]
Section 13.2.1 Quanitfish link goes to a twitter post

**Comment by CataRoman** [comment]
Lab meeting time changed

**Comment by CataRoman** [comment]
Update lab members photos (madeleine was working on this)

**Comment by CataRoman** [comment]
Update Southcoast useR group (still active?) Seems like the last meeting was 2022
Same with Shut Up and Write

**Comment by KamranWalsh** [comment]
@gavinfay will update photo
