### ISSUE TITLE
10/21 Manual Review: Offboarding Changes

### ISSUE THREAD

**Issue by se-hope** [thefaylab/lab-manual#52]
- First mention of lab library - maybe we include a list of resources available in the physical lab space 
- Point 7.3 publications and presentations. Add a link to the Google drive folder with shared presentations. 
- Point 7.8 Lab library. Add a list of available books and the name of the student that is currently using it in case someone else needs the same book. Remember to not keep the books in your desk if you are not using it.

**Comment by MaC-Perez** [comment]
add link with books inventory and ask other students if they have any FayLab book in their desks.  @

**Comment by MaC-Perez** [comment]
added. book and power points guidelines
